name: daily_log
description: A new Flutter project.

publish_to: "none"
version: 1.2.0+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  path: ^1.8.0
  path_provider: ^2.0.1
  provider: ^4.3.3
  bloc: ^6.1.3
  flutter_bloc: ^6.1.3
  equatable: ^2.0.0
  json_annotation: ^3.1.1
  table_calendar: ^2.3.3
  badges: ^1.2.0
  flutter_slidable: ^0.5.7
  flutter_colorpicker: ^0.3.5
  firebase_core: ^1.0.1
  firebase_crashlytics: ^1.0.0
  sembast: ^3.0.0+4

dev_dependencies:
  test: ^1.15.7
  bloc_test: ^7.1.0
  mockito: ^4.1.3
  build_runner: ^1.11.5
  json_serializable: ^3.5.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
