name: daily_log
description: A new Flutter project.

publish_to: "none"
version: 1.1.1+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.1
  path: ^1.7.0
  path_provider: ^1.6.24
  provider: ^4.3.2+2
  bloc: ^6.1.0
  flutter_bloc: ^6.1.1
  equatable: ^1.2.5
  json_annotation: ^3.1.1
  table_calendar: ^2.3.0
  badges: ^1.1.4
  flutter_slidable: ^0.5.7
  flutter_colorpicker: ^0.3.4
  firebase_core: ^0.5.2
  firebase_crashlytics: ^0.2.3
  sembast: ^2.4.8

dev_dependencies:
  test: ^1.15.7
  bloc_test: ^7.1.0
  mockito: ^4.1.3
  build_runner: ^1.10.6
  json_serializable: ^3.5.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
